#!/bin/sh
set -e

CONFIG_PATH=/data/options.json
cat /data/options.json
JFLATNOTES_AUTH_TYPE='none'
FLATNOTES_AUTH_TYPE=$(jq --raw-output '.FLATNOTES_AUTH_TYPE' $CONFIG_PATH)
echo "FLATNOTES_AUTH_TYPE: ${FLATNOTES_AUTH_TYPE}"
export FLATNOTES_AUTH_TYPE="${FLATNOTES_AUTH_TYPE}"

FLATNOTES_USERNAME='none'
FLATNOTES_USERNAME=$(jq --raw-output '.FLATNOTES_USERNAME' $CONFIG_PATH)
echo "FLATNOTES_USERNAME: ${FLATNOTES_USERNAME}"
export FLATNOTES_USERNAME="${FLATNOTES_USERNAME}"

FLATNOTES_SECRET_KEY='none'
FLATNOTES_SECRET_KEY=$(jq --raw-output '.FLATNOTES_SECRET_KEY' $CONFIG_PATH)
echo "FLATNOTES_SECRET_KEY: ${FLATNOTES_SECRET_KEY}"
export FLATNOTES_SECRET_KEY="${FLATNOTES_SECRET_KEY}"

FLATNOTES_SESSION_EXPIRY_DAYS='30'
FLATNOTES_SESSION_EXPIRY_DAYS=$(jq --raw-output '.FLATNOTES_SESSION_EXPIRY_DAYS' $CONFIG_PATH)
echo "FLATNOTES_SESSION_EXPIRY_DAYS: ${FLATNOTES_SESSION_EXPIRY_DAYS}"
export FLATNOTES_SESSION_EXPIRY_DAYS="${FLATNOTES_SESSION_EXPIRY_DAYS}"

FLATNOTES_TOTP_KEY='none'
FLATNOTES_TOTP_KEY=$(jq --raw-output '.FLATNOTES_TOTP_KEY' $CONFIG_PATH)
echo "FLATNOTES_TOTP_KEY: ${FLATNOTES_TOTP_KEY}"
export FLATNOTES_TOTP_KEY="${FLATNOTES_TOTP_KEY}"

/entrypoint.sh