#!/bin/bash
set -e

CONFIG_PATH=/data/options.json
cat /data/options.json

TITLE=$(jq --raw-output '.TITLE' $CONFIG_PATH)
echo "TITLE: ${TITLE}"
export TITLE="${TITLE}"

LOGO=$(jq --raw-output '.LOGO' $CONFIG_PATH)
echo "LOGO: ${LOGO}"
export LOGO="${LOGO}"

GALLERY_COLUMNS=$(jq --raw-output '.GALLERY_COLUMNS' $CONFIG_PATH)
echo "GALLERY_COLUMNS: ${GALLERY_COLUMNS}"
export GALLERY_COLUMNS="${GALLERY_COLUMNS}"

ALLOWED_FILE_TYPES=$(jq --raw-output '.ALLOWED_FILE_TYPES' $CONFIG_PATH)
echo "ALLOWED_FILE_TYPES: ${ALLOWED_FILE_TYPES}"
export ALLOWED_FILE_TYPES="${ALLOWED_FILE_TYPES}"

ADMIN_PASSWORD=$(jq --raw-output '.ADMIN_PASSWORD' $CONFIG_PATH)
echo "ADMIN_PASSWORD: ${ADMIN_PASSWORD}"
export ADMIN_PASSWORD="${ADMIN_PASSWORD}"
  
SINGLE_GALLERY_MODE=$(jq --raw-output '.SINGLE_GALLERY_MODE' $CONFIG_PATH)
echo "SINGLE_GALLERY_MODE: ${SINGLE_GALLERY_MODE}"
export SINGLE_GALLERY_MODE="${SINGLE_GALLERY_MODE}"

REQUIRE_REVIEW=$(jq --raw-output '.REQUIRE_REVIEW' $CONFIG_PATH)
echo "REQUIRE_REVIEW: ${REQUIRE_REVIEW}"
export REQUIRE_REVIEW="${REQUIRE_REVIEW}"

DISABLE_HOME_LINK=$(jq --raw-output '.DISABLE_HOME_LINK' $CONFIG_PATH)
echo "DISABLE_HOME_LINK: ${DISABLE_HOME_LINK}"
export DISABLE_HOME_LINK="${DISABLE_HOME_LINK}"

DISABLE_REVIEW_COUNTER=$(jq --raw-output '.DISABLE_REVIEW_COUNTER' $CONFIG_PATH)
echo "DISABLE_REVIEW_COUNTER: ${DISABLE_REVIEW_COUNTER}"
export DISABLE_REVIEW_COUNTER="${DISABLE_REVIEW_COUNTER}"

DISABLE_UPLOAD=$(jq --raw-output '.DISABLE_UPLOAD' $CONFIG_PATH)
echo "DISABLE_UPLOAD: ${DISABLE_UPLOAD}"
export DISABLE_UPLOAD="${DISABLE_UPLOAD}"

DISABLE_QR_CODE=$(jq --raw-output '.DISABLE_QR_CODE' $CONFIG_PATH)
echo "DISABLE_QR_CODE: ${DISABLE_QR_CODE}"
export DISABLE_QR_CODE="${DISABLE_QR_CODE}"

DISABLE_GUEST_GALLERY_CREATION=$(jq --raw-output '.DISABLE_GUEST_GALLERY_CREATION' $CONFIG_PATH)
echo "DISABLE_GUEST_GALLERY_CREATION: ${DISABLE_GUEST_GALLERY_CREATION}"
export DISABLE_GUEST_GALLERY_CREATION="${DISABLE_GUEST_GALLERY_CREATION}"

HIDE_KEY_FROM_QR_CODE=$(jq --raw-output '.HIDE_KEY_FROM_QR_CODE' $CONFIG_PATH)
echo "HIDE_KEY_FROM_QR_CODE: ${HIDE_KEY_FROM_QR_CODE}"
export HIDE_KEY_FROM_QR_CODE="${HIDE_KEY_FROM_QR_CODE}"

IDLE_GALLERY_REFRESH_MINS=$(jq --raw-output '.IDLE_GALLERY_REFRESH_MINS' $CONFIG_PATH)
echo "IDLE_GALLERY_REFRESH_MINS: ${IDLE_GALLERY_REFRESH_MINS}"
export IDLE_GALLERY_REFRESH_MINS="${IDLE_GALLERY_REFRESH_MINS}"

cd /app
dotnet WeddingShare.dll