#!/bin/sh
set -e

CONFIG_PATH=/data/options.json

HBOX_OPTIONS_ALLOW_REGISTRATION=$(jq --raw-output '.HBOX_OPTIONS_ALLOW_REGISTRATION // empty' $CONFIG_PATH)
echo "HBOX_OPTIONS_ALLOW_REGISTRATION: ${HBOX_OPTIONS_ALLOW_REGISTRATION}"
export HBOX_OPTIONS_ALLOW_REGISTRATION="${HBOX_OPTIONS_ALLOW_REGISTRATION}"

/app/api
