name: searxng-mcp-server
version: "1.1"
upstream: "1.0"
slug: searxngmcpserver
description: >-
  An MCP sse implementation of the Model Context Protocol (MCP) server integrated with SearXNG for providing AI agents with powerful, privacy-respecting search capabilities.
arch:
  - amd64
  - aarch64
url: "https://github.com/jdeath/homeassistant-addons"
ports:
  8081/tcp: 8081 
ports_description:
  8081/tcp: "API Interface"
map:
  - type: addon_config
    read_only: false
environment:
    MCP_HTTP_HOST: "0.0.0.0"
    MCP_HTTP_PORT: "8081"
    ODS_CONFIG_PATH: "/config/ods_config.json"
options:
    SEARXNG_ENGINE_API_BASE_URL: "http://172.17.0.1:8080/search"
schema:
    SEARXNG_ENGINE_API_BASE_URL: "str"
boot: manual
#host_pid: true
init: false
startup: services